kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cu-user-access
  namespace: cu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cu-user-full-access
subjects:
- kind: Group
  namespace: cu
  name: 5888443a-ba33-4e36-95f5-3b8eaf15cd5e